### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by anbraten** [anbraten/ourhome#1]
# TODO

- [x] login
  - [ ] show pretty email not verified message
- [x] check login status and redirect accordingly
- [x] register new user
- [ ] don't block for initial api load?
- [x] create share
- [ ] share settings
  - [ ] invite user to share
  - [ ] delete share
  - [ ] change name
  - [ ] set share default currency
- [x] pinboard
  - [x] create post
  - [x] delete post
  - [ ] add post types
    - [x] expense
    - [ ] task
- [ ] expenses
  - [ ] dropdown for members for `paid by`, `paid for`
  - [ ] currency dropdown
- [ ] finances
  - [ ] new payment (amount, from, to)
  - [ ] new payment via paypal.me
- [ ] profile
  - [ ] change name
  - [ ] change password
  - [ ] set profile picture
  - [ ] delete account
  - [ ] set language?
  - [ ] set paypal name
- [ ] technical
  - [ ] use store and inject / project 
    - [ ] load share once and register update hooks
    - [ ] load share members once and register update hooks
